export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_ALL_EVENTS = 'DELETE_ALL_EVENTS';

export const ADD_OPEATION_LOG = 'ADD_OPEATION_LOG';
export const DELETE_ALL_OPEATION_LOGS = 'DELETE_ALL_OPEATION_LOGS';
